---
git:
  branch: main
triggers:
  cron: "@daily"
clean_workspace: true
builders:
  - script
docker_name: bankid-idp
docker_no_cache: true
docker_force_pull: false
environment_variables:
  UPSTREAM_VERSIONS: "1.1.2 1.2.1 1.2.3"
script:
  - ./build.sh
