---
git:
  branch: main
triggers:
  cron: "@daily"
clean_workspace: true
builders:
  - docker
docker_name: bankid-idp
docker_tags:
  - SUNET-1
  - "latest"
docker_no_cache: true
docker_force_pull: false
environment_variables:
  UPSTREAM_VERSION: "fixbranch-1.1"
pre_build_script:
  - ./build.sh
